import type { GetServerSideProps, NextPage } from "next"
import Head from "next/head"
import Navigation from "../components/Navigation"
import Main from "../components/Main"
import Header from "../components/Header"
import useToken from "../lib/hooks/useToken"
import Player from "../components/Player"

const Home: NextPage = () => {
  const token = useToken()
  return (
    <div>
      <Head>
        <title>Spotify App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <div className="flex-none">
          <Navigation />
        </div>
        <div className="flex-grow bg-[#121212]">
          <Header />
          <Main />
        </div>
        <div className="w-full  h-[90px] bg-[#181818] fixed bottom-0 ">
          <Player />
        </div>
      </div>
    </div>
  )
}

export default Home
